# [target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-apple-darwin]
# Uncomment instead of default rustflags for better performance. Requires zld via `brew install michaeleisel/zld/zld`
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Z", "share-generics=y"]
rustflags = ["-Z", "share-generics=y"]

[target.aarch64-apple-darwin]
# Uncomment instead of default rustflags for better performance. Requires zld via `brew install michaeleisel/zld/zld`
# rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/bin/zld", "-Z", "share-generics=y"]
rustflags = ["-Z", "share-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    "-Zshare-generics=n",
    "-Ctarget-feature=+crt-static",
]

# Enable no optimization in debug mode. You should probably bump this up for Wasm builds.
[profile.dev]
opt-level = 0
# Optional: Uncommenting the following improves compile times, but reduces the amount of debug info to 'line number tables only'
# In most cases the gains are negligible, but if you are on macos and have slow compile times you should see significant gains.
# debug = 1

# Enable some optimizations for dependencies (incl. Bevy), but not for our code. You should probably bump this up for Wasm builds.
[profile.dev.package."*"]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1

[build]
target = "x86_64-pc-windows-gnu"